export type FieldType = "N" | "#";

export type HandbookField = {
  id: string;
  type: FieldType;
  feedsInto: string[];
  question: string;
  example: string;
  multiline?: boolean;
};

export type HandbookSection = {
  id: string;
  title: string;
  description: string;
  fields: HandbookField[];
};

export const HANDBOOK: HandbookSection[] = [
  {
    id: "FM",
    title: "Front Matter: Co-op Identity",
    description: "Lock in the basics before you dive into the full journey. These fields appear on every output document — they're the identity of your co-op.",
    fields: [
      {
        id: "FM-01",
        type: "N",
        feedsInto: ["All 10 output documents"],
        question: "What is the name of your cooperative?",
        example: "Neighbors Care Cooperative",
        multiline: false,
      },
      {
        id: "FM-02",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch"],
        question: "Write your co-op's tagline — one sentence that captures what you do and why it matters.",
        example: "Worker-owned home care that keeps neighbors healthy, employed, and rooted in Lansing.",
        multiline: false,
      },
      {
        id: "FM-03",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch", "Ecosystem Map"],
        question: "What city, neighborhood, or region do you primarily serve?",
        example: "Lansing, Michigan — primarily the Eastside and North Lansing neighborhoods.",
        multiline: false,
      },
      {
        id: "FM-04",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "P&L", "Pitch"],
        question: "What industry or sector is your co-op in? (food, care, construction, tech, energy, etc.)",
        example: "Home care and personal assistance services.",
        multiline: false,
      },
      {
        id: "FM-05",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Governance Summary", "Scorecard", "Pitch"],
        question: "List your co-op's 3 to 5 core values — the non-negotiable principles that guide every decision.",
        example: "Dignity, democratic ownership, living wages, community rootedness, radical inclusion.",
        multiline: true,
      },
      {
        id: "FM-06",
        type: "N",
        feedsInto: ["Executive Summary", "Scorecard", "Governance Summary", "Pitch"],
        question: "State your specific ethical commitments — on wages, governance, environment, and community.",
        example: "We commit to paying every worker-owner at least $18/hour (Lansing living wage). We commit to one worker, one vote governance. We commit to sourcing locally wherever possible. We commit to reinvesting surplus into our members and our community.",
        multiline: true,
      },
      {
        id: "FM-07",
        type: "#",
        feedsInto: ["Executive Summary", "Governance Summary", "Equity Schedule"],
        question: "What month and year do you plan to formally incorporate?",
        example: "March 2026",
        multiline: false,
      },
    ],
  },
  {
    id: "P1",
    title: "Part One: Our Founding Story",
    description: "People don't join businesses. They join movements. Tell them why this one matters. Work through these prompts as a group — write your answers down, argue about them a little. What comes out the other side is your real story.",
    fields: [
      {
        id: "P1-01",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch"],
        question: "Who are we? Describe the founding group in human terms — where you come from, what you've lived, what connects you. Not job titles. Not résumés. Who are the people in this room?",
        example: "We are six home care workers from Lansing who have spent a combined 40 years caring for seniors and people with disabilities. We've all worked for agencies that paid us poverty wages while charging families high rates. We're tired of working hard and watching the money go somewhere else.",
        multiline: true,
      },
      {
        id: "P1-02",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch", "Scorecard"],
        question: "What did we see that wasn't working? The specific problem or gap that led to this co-op. Be specific — generic problems get generic solutions.",
        example: "Home care agencies in Lansing pay caregivers $10–12/hour while charging families $28–35/hour. Workers have no benefits, no stability, no voice. Families get inconsistent care because workers keep leaving. Everyone loses except the agency owner.",
        multiline: true,
      },
      {
        id: "P1-03",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "P&L", "Pitch"],
        question: "What are we building — and for whom? Plain language. No jargon. If you can't explain it to your neighbor in two sentences, keep working on it.",
        example: "We are building a worker-owned home care cooperative that employs caregivers as owner-members, pays living wages, and provides consistent, high-quality care to seniors and people with disabilities in Lansing.",
        multiline: true,
      },
      {
        id: "P1-04",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch"],
        question: "Who do we serve? Describe your primary beneficiaries — your worker-owners, your customers, and your community.",
        example: "Our worker-owners: experienced caregivers who deserve ownership, living wages, and dignity. Our customers: seniors and adults with disabilities who need consistent, trustworthy in-home care. Our community: Lansing neighborhoods where we live and work.",
        multiline: true,
      },
      {
        id: "P1-05",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Governance Summary", "Pitch"],
        question: "Why a cooperative — and not just another business? What does shared ownership mean to your founding group specifically?",
        example: "Because we've been the workers. We know what it feels like when someone else owns your labor. A cooperative means we set our own wages, we make the decisions, and when the business does well — we do well. No one extracts from us.",
        multiline: true,
      },
      {
        id: "P1-06",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Scorecard", "Pitch"],
        question: "What does success look like in 10 years if everything goes right? Dare to dream out loud.",
        example: "In 10 years, Neighbors Care has 40 worker-owners all earning above the living wage with full benefits. We've helped start two more co-ops in Lansing. Our model has been replicated in three other Michigan cities. No caregiver in our network lives in poverty.",
        multiline: true,
      },
      {
        id: "P1-07",
        type: "N",
        feedsInto: ["Executive Summary", "Pitch"],
        question: "Write your 90-second story: the problem, your solution, and the invitation. Practice this out loud until a stranger can repeat it back to you.",
        example: "Home care in Lansing is broken. Caregivers earn poverty wages while agencies pocket the difference. Families get strangers who keep quitting. We're building Neighbors Care Cooperative — where the caregivers own the agency. We pay living wages, we hire for keeps, and every member has a vote. If you need care for someone you love, or you're a caregiver who's tired of being undervalued — we want to talk to you.",
        multiline: true,
      },
      {
        id: "P1-08",
        type: "N",
        feedsInto: ["Executive Summary", "Ecosystem Map", "Pitch"],
        question: "How does your co-op connect to the larger Project 2026 vision? How does it fit the ecosystem?",
        example: "Home care is one of the 10 basic needs Project 2026 is building cooperative solutions for. Neighbors Care is the healthcare node in Lansing's cooperative ecosystem — employing ALICE workers, serving ALICE households, and keeping value in the community instead of extracting it.",
        multiline: true,
      },
    ],
  },
  {
    id: "P2",
    title: "Part Two: Building Your Ownership Community",
    description: "We're not looking for investors. We're looking for people who want to be part of something they actually own. In a worker-owned cooperative, ownership isn't something you add later. It's the point.",
    fields: [
      {
        id: "P2-01",
        type: "#",
        feedsInto: ["Executive Summary", "Equity Schedule", "Governance Summary", "Startup Budget"],
        question: "How many people are in your founding group? (This is the number of worker-owners starting this co-op together.)",
        example: "6 founding worker-owners",
        multiline: false,
      },
      {
        id: "P2-02",
        type: "N",
        feedsInto: ["Executive Summary", "Governance Summary"],
        question: "List your founding members and what each person brings to the co-op — skills, relationships, experience, lived knowledge.",
        example: "Maria (15 yrs caregiving, bilingual Spanish/English), James (10 yrs caregiving, CPR trainer), Daria (7 yrs caregiving, former union organizer), Keisha (12 yrs caregiving, client relations), Tom (8 yrs caregiving, van driver), Linda (20 yrs caregiving, mentor).",
        multiline: true,
      },
      {
        id: "P2-03",
        type: "#",
        feedsInto: ["Equity Schedule", "Startup Budget", "Cash Flow"],
        question: "What is the membership buy-in amount? (What does each worker pay to become a full member-owner? Should be accessible — not a barrier.)",
        example: "$500 per member, payable through $25/month payroll deduction over 20 months",
        multiline: false,
      },
      {
        id: "P2-04",
        type: "N",
        feedsInto: ["Equity Schedule", "Governance Summary"],
        question: "How will the buy-in be paid? (Lump sum, payroll deduction, labor contribution, other arrangement?)",
        example: "Payroll deduction of $25/month over 20 months. No one is excluded for inability to pay upfront.",
        multiline: true,
      },
      {
        id: "P2-05",
        type: "#",
        feedsInto: ["Governance Summary", "Equity Schedule"],
        question: "How long is the probationary period before a worker becomes a full voting member? (Typical range: 3–6 months.)",
        example: "4 months",
        multiline: false,
      },
      {
        id: "P2-06",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "What will new members learn during the probationary period and cooperative education program?",
        example: "ICA Seven Cooperative Principles, how our financials work (open book), how governance and voting work, what it means to be an owner not just an employee, Neighbors Care policies and values.",
        multiline: true,
      },
      {
        id: "P2-07",
        type: "#",
        feedsInto: ["Equity Schedule", "Executive Summary", "Scorecard"],
        question: "How many worker-owners do you aim to have by the end of Year 3?",
        example: "20 worker-owners",
        multiline: false,
      },
      {
        id: "P2-08",
        type: "N",
        feedsInto: ["Executive Summary", "Ecosystem Map", "Pitch"],
        question: "Who are the community supporters of your co-op? (People who believe in what you're building and want to support it — through purchases, referrals, advocacy.)",
        example: "Faith communities on Lansing's Eastside, Area Agency on Aging, CATA (transit), neighborhood associations, The Fledge community.",
        multiline: true,
      },
      {
        id: "P2-09",
        type: "N",
        feedsInto: ["Ecosystem Map", "Canvas"],
        question: "Which other co-ops or community organizations do you want to partner with? How does that connection trap value locally?",
        example: "Urbandale Farm (food co-op — we refer clients for food delivery), Sunshine House (housing co-op — shared members), local credit union for member savings accounts. Every dollar stays in Lansing.",
        multiline: true,
      },
      {
        id: "P2-10",
        type: "N",
        feedsInto: ["Pitch"],
        question: "Write your 90-second neighborhood conversation — someone at a community event asks what you're working on. You're not selling, you're inviting. Practice it out loud.",
        example: "We're starting a home care co-op where the caregivers own the business. We pay living wages, provide consistent care, and every worker has a vote. If you know someone who needs home care — or a caregiver tired of being undervalued — we'd love to talk.",
        multiline: true,
      },
    ],
  },
  {
    id: "P3",
    title: "Part Three: Who We Serve",
    description: "You can't serve everyone. And if you try, you'll serve no one well. But in a co-op, 'who we serve' includes the people doing the serving — worker-owners, customers, and the broader community.",
    fields: [
      {
        id: "P3-WO",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard", "Executive Summary"],
        question: "What does a genuinely good job look like for the people in this co-op? What wages, conditions, and ownership experience are you committing to?",
        example: "Living wage ($18/hr minimum), consistent full-time hours, paid time off, democratic voice in all major decisions, growing equity through capital accounts, no more working for poverty wages while someone else profits.",
        multiline: true,
      },
      {
        id: "P3-01",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch"],
        question: "Customer Profile 1: Give them a name. Describe their daily life, their needs, their frustrations, and what a win looks like for them.",
        example: "Ruth, 78, lives alone on the Eastside. Her daughter lives in Detroit and worries constantly. Ruth needs help with bathing, meals, and rides to appointments. She's had 6 different aides in 2 years because agencies keep sending whoever is available. She wants someone she knows and trusts.",
        multiline: true,
      },
      {
        id: "P3-02",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas"],
        question: "Customer Profile 2: A different type of person who benefits from your co-op.",
        example: "Marcus, 45, has a physical disability and works part-time. He needs morning and evening assistance and is on Medicaid waiver. He wants a caregiver who respects his independence and doesn't treat him like a patient.",
        multiline: true,
      },
      {
        id: "P3-03",
        type: "N",
        feedsInto: ["Canvas"],
        question: "Customer Profile 3 (optional): A third type of customer or community member your co-op serves.",
        example: "The Chen family — adult children who work full-time and need reliable care for their mother who has early-stage dementia. They're paying privately and want consistency, communication, and peace of mind.",
        multiline: true,
      },
      {
        id: "P3-04",
        type: "N",
        feedsInto: ["Executive Summary", "Canvas", "Pitch"],
        question: "Write your value proposition: one sentence answering \"why should someone choose your co-op?\" Include what ownership makes different.",
        example: "Neighbors Care provides consistent, dignified home care from worker-owners who chose this work — because when caregivers own the agency, they stay, they care, and your family gets the stability they deserve.",
        multiline: true,
      },
      {
        id: "P3-05",
        type: "#",
        feedsInto: ["P&L", "Executive Summary"],
        question: "Roughly how many people in your service area need what your co-op offers? (A rough estimate is fine — this helps size your market.)",
        example: "Ingham County has approximately 8,400 seniors who need in-home assistance and an estimated 2,200 working-age adults with disabilities who use home care services.",
        multiline: false,
      },
      {
        id: "P3-06",
        type: "N",
        feedsInto: ["Executive Summary", "Scorecard", "Pitch"],
        question: "How is your broader community stronger because your co-op exists? Go beyond your immediate customers.",
        example: "We create living-wage jobs for workers who are mostly women, mostly people of color, mostly from ALICE households. We keep money in Lansing. We provide care that keeps seniors out of more expensive facilities. We prove that cooperative business works.",
        multiline: true,
      },
      {
        id: "P3-07",
        type: "N",
        feedsInto: ["Scorecard", "Governance Summary"],
        question: "How will you make your co-op accessible to people across income levels, languages, and abilities?",
        example: "We accept Medicaid waiver clients (not just private pay). We have bilingual Spanish-speaking worker-owners. We keep our intake process simple and human — no complicated forms. We partner with community organizations to reach families who wouldn't otherwise find us.",
        multiline: true,
      },
    ],
  },
  {
    id: "P4",
    title: "Part Four: Channels — How Value Reaches People",
    description: "The best service in the world doesn't matter if the people who need it can't find it. A channel is how your product or service gets from your co-op to the person who needs it — and how potential member-owners and partners find you.",
    fields: [
      {
        id: "P4-01",
        type: "N",
        feedsInto: ["Canvas", "Startup Budget"],
        question: "What is your primary channel — the main way customers and potential members find you? Describe it specifically.",
        example: "Referrals from the Area Agency on Aging, hospital social workers, and Medicaid case managers. These professionals are always looking for reliable home care options and will refer families directly to us.",
        multiline: true,
      },
      {
        id: "P4-02",
        type: "N",
        feedsInto: ["Canvas", "Startup Budget"],
        question: "What is your second channel? How does it complement the first?",
        example: "Community presence — showing up at faith communities, neighborhood association meetings, and Fledge events. Builds trust and name recognition in the neighborhoods we serve.",
        multiline: true,
      },
      {
        id: "P4-03",
        type: "N",
        feedsInto: ["Canvas"],
        question: "What is your third channel? Why does this one make sense for your co-op?",
        example: "A simple website and Facebook page. Many families search online first. We don't need to be fancy — we need to be findable and credible.",
        multiline: true,
      },
      {
        id: "P4-04",
        type: "#",
        feedsInto: ["Startup Budget", "P&L", "Cash Flow"],
        question: "What is your estimated total monthly cost to operate all your channels? (Marketing, advertising, website hosting, event fees, etc.)",
        example: "$400/month — $150 website/hosting, $150 community events and printed materials, $100 social media boosting",
        multiline: false,
      },
      {
        id: "P4-05",
        type: "N",
        feedsInto: ["Governance Summary", "Ecosystem Map"],
        question: "Which channel is most likely to reach future worker-owners — people who might want to join your co-op as member-owners?",
        example: "Word of mouth through existing caregivers and community organizations. The best recruitment is a worker-owner telling their colleague: \"I own my job now. Come join us.\"",
        multiline: true,
      },
      {
        id: "P4-06",
        type: "N",
        feedsInto: ["Ecosystem Map", "Canvas"],
        question: "How will you connect with and through other co-ops in the ecosystem?",
        example: "Monthly connection with Fledge co-ops. Cross-referrals with Urbandale Farm. Shared member recruitment with Sunshine House. Attending Project 2026 community events together.",
        multiline: true,
      },
    ],
  },
  {
    id: "P5",
    title: "Part Five: Relationships",
    description: "A channel gets you in front of someone once. A relationship keeps them coming back — and gets them to bring their friends. Relationships run in three directions: between worker-owners, between your co-op and customers, and between your co-op and the community.",
    fields: [
      {
        id: "P5-01",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard", "Executive Summary"],
        question: "What is the standard for how worker-owners treat each other in your co-op? What can every member-owner expect from the group?",
        example: "Every worker-owner is treated as an equal regardless of seniority or hours. We make decisions together. We disagree respectfully. We don't gossip about each other to clients. We bring problems to the group, not to social media.",
        multiline: true,
      },
      {
        id: "P5-02",
        type: "N",
        feedsInto: ["Canvas", "Executive Summary"],
        question: "How does your co-op build and maintain trust with customers? What is your relationship standard — what can every customer expect from you?",
        example: "Every client gets a consistent caregiver — not whoever is available that day. We communicate proactively when anything changes. We treat every client with dignity regardless of income level or payment method. We never make someone feel like a burden.",
        multiline: true,
      },
      {
        id: "P5-04",
        type: "#",
        feedsInto: ["P&L", "Scorecard"],
        question: "What customer retention rate are you targeting? (What percentage of customers do you aim to keep year over year?)",
        example: "85% annual client retention rate. Industry average for traditional agencies is around 60–65%. Our ownership model should drive significantly higher retention.",
        multiline: false,
      },
      {
        id: "P5-03",
        type: "N",
        feedsInto: ["Scorecard", "Ecosystem Map", "Executive Summary"],
        question: "How does your co-op stay connected to and accountable to the broader community — beyond your immediate customers and members?",
        example: "We attend neighborhood association meetings. We show up at community events. We partner with faith communities and social service organizations. We report our impact publicly every year — wages paid, clients served, money kept local.",
        multiline: true,
      },
      {
        id: "P5-05",
        type: "#",
        feedsInto: ["Scorecard", "Governance Summary"],
        question: "How will you measure worker-owner satisfaction? Describe the scale or method you'll use.",
        example: "Anonymous quarterly survey, scale of 1–10. Target: average score of 8 or above. Any score below 7 triggers a member meeting within 30 days.",
        multiline: true,
      },
    ],
  },
  {
    id: "P6",
    title: "Part Six: Branding",
    description: "Your brand is not your logo. Your brand is the feeling people get when they think about you. For a worker-owned cooperative, your brand has something most businesses can't claim: the people who serve you own the business.",
    fields: [
      {
        id: "P6-01",
        type: "N",
        feedsInto: ["Canvas", "Pitch", "Executive Summary"],
        question: "What are the three words you want people to associate with your co-op? Not what you do — how you make people feel.",
        example: "Trustworthy. Dignified. Rooted.",
        multiline: false,
      },
      {
        id: "P6-02",
        type: "N",
        feedsInto: ["Executive Summary", "Pitch"],
        question: "Write your brand story — the authentic, specific narrative of why this co-op exists and why your founding group is the one to build it.",
        example: "Neighbors Care was started by six caregivers who spent years providing excellent care for poverty wages while agency owners kept the difference. We got tired of being invisible. We knew the work. We knew the families. We just didn't own it. Now we do. And that changes everything about how we show up.",
        multiline: true,
      },
      {
        id: "P6-03",
        type: "N",
        feedsInto: ["Canvas"],
        question: "Describe your visual identity — the colors, tone, and imagery that represent your co-op. What feeling should someone get when they see your materials?",
        example: "Warm and human — photos of real people, not stock images. Colors: deep green (growth, care) and warm gold (dignity, value). No clinical imagery. We are neighbors, not a corporation.",
        multiline: true,
      },
      {
        id: "P6-04",
        type: "N",
        feedsInto: ["Canvas", "Startup Budget"],
        question: "What is your content and communication plan? How often and where will you show up publicly?",
        example: "Monthly community newsletter (email + printed for non-digital neighbors). Weekly Facebook post. Quarterly presence at community events. Annual impact report shared publicly.",
        multiline: true,
      },
      {
        id: "P6-05",
        type: "#",
        feedsInto: ["Startup Budget", "P&L", "Cash Flow"],
        question: "What is your estimated monthly marketing and communications budget?",
        example: "$400/month — printing, design, social media, event presence",
        multiline: false,
      },
    ],
  },
  {
    id: "P7",
    title: "Part Seven: The Four Bottom Lines in Practice",
    description: "If you're winning on profit but losing on people, planet, or ownership — you're not winning. You're borrowing against a debt someone else will pay. This is where values meet measurements.",
    fields: [
      {
        id: "P7-01",
        type: "N",
        feedsInto: ["Scorecard", "Executive Summary"],
        question: "What does treating people with dignity look like specifically in your co-op? Name three concrete practices you will commit to.",
        example: "1. Every worker-owner earns at least the Lansing living wage from day one. 2. No worker is scheduled without at least 72 hours notice. 3. Every client concern is addressed within 24 hours by a member-owner, not a call center.",
        multiline: true,
      },
      {
        id: "P7-02",
        type: "#",
        feedsInto: ["P&L", "Startup Budget", "Scorecard", "Equity Schedule"],
        question: "What is your living wage target — the minimum hourly wage every worker-owner will earn? (Look up the current living wage for your area at livingwage.mit.edu)",
        example: "$18.50/hour — the 2026 living wage for a single adult in Ingham County, Michigan",
        multiline: false,
      },
      {
        id: "P7-03",
        type: "#",
        feedsInto: ["Governance Summary", "Scorecard", "Equity Schedule"],
        question: "What is your maximum wage ratio — the highest-to-lowest pay ratio allowed in your co-op? (Mondragon uses 5:1. Many small co-ops use 3:1.)",
        example: "3:1. No worker-owner earns more than three times what the lowest-paid member earns.",
        multiline: false,
      },
      {
        id: "P7-04",
        type: "N",
        feedsInto: ["Scorecard", "Executive Summary"],
        question: "What are your specific environmental commitments? What will your co-op do — and not do — to protect the planet?",
        example: "We use fuel-efficient or hybrid vehicles for client transportation where possible. We source supplies locally to reduce shipping emissions. We reduce paper by using digital care logs. We champion green practices in the homes we work in.",
        multiline: true,
      },
      {
        id: "P7-05",
        type: "#",
        feedsInto: ["Scorecard"],
        question: "Name one specific, measurable environmental goal your co-op will track. (Example: 80% of supplies sourced within 50 miles.)",
        example: "80% of cleaning and care supplies sourced from Michigan-based vendors within the first year.",
        multiline: false,
      },
      {
        id: "P7-06",
        type: "N",
        feedsInto: ["Executive Summary", "Scorecard", "P&L"],
        question: "What is surplus for in your co-op? Write a clear statement about how profit will be used — for wages, reinvestment, member equity, and community benefit.",
        example: "Any surplus above our operating reserve is allocated: 40% to member capital accounts as patronage dividends, 40% reinvested in co-op growth and reserves, 20% to community benefit — sponsoring neighborhood programs or supporting new co-op startups in Lansing.",
        multiline: true,
      },
      {
        id: "P7-07",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "What does genuine democratic governance look like in your co-op on a day-to-day basis? Not just in theory — in practice.",
        example: "Monthly member meetings where every decision above $500 is brought to the full group. Rotating facilitation so no one person dominates. Anonymous suggestion process for concerns people aren't ready to raise publicly. Annual governance review where we ask: is this actually working?",
        multiline: true,
      },
      {
        id: "P7-08",
        type: "#",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "What percentage of member-owners voting in governance decisions do you consider healthy? What would trigger a concern?",
        example: "Target: 80% participation in all major votes. If participation drops below 60% for two consecutive meetings, we call a special meeting to find out why.",
        multiline: true,
      },
    ],
  },
  {
    id: "P8",
    title: "Part Eight: Resources — What We Have and What We Need",
    description: "Don't try to build everything alone. That's what the ecosystem is for. Getting clear about what you have and what you need is how you build a realistic plan — and avoid the most common mistake new co-ops make: underestimating startup costs.",
    fields: [
      {
        id: "P8-08",
        type: "N",
        feedsInto: ["Startup Budget", "Executive Summary"],
        question: "What resources does your founding group already have in hand? Be specific — equipment, space, skills, relationships, tools, licenses.",
        example: "6 experienced caregivers with active certifications. Two members have their own reliable vehicles. One member has bookkeeping experience. We have a relationship with the Area Agency on Aging who has offered to refer clients immediately. The Fledge is providing meeting space and coaching at no cost.",
        multiline: true,
      },
      {
        id: "P8-01",
        type: "#",
        feedsInto: ["Startup Budget", "Cash Flow"],
        question: "Equipment costs: What tools, technology, or machinery do you need to buy or lease to operate? List items and total cost.",
        example: "$3,200 total — 2 used vehicles leased ($800/month combined, first month = $800), care management software setup ($1,200), uniforms and PPE for 6 workers ($600), office supplies and printer ($600)",
        multiline: true,
      },
      {
        id: "P8-02",
        type: "#",
        feedsInto: ["Startup Budget", "P&L", "Cash Flow"],
        question: "Space and facility: Do you need a physical location? What does it cost per month? (Many co-ops start from home or shared space — that's fine.)",
        example: "$0 initially — operating from members' homes and using The Fledge for meetings. Budget $500/month for a small office in Year 2.",
        multiline: false,
      },
      {
        id: "P8-03",
        type: "#",
        feedsInto: ["Startup Budget", "Cash Flow"],
        question: "Starting inventory or supplies: What stock of materials, products, or supplies do you need before you open?",
        example: "$800 — cleaning supplies, personal care products, first aid kits, care documentation forms",
        multiline: false,
      },
      {
        id: "P8-04",
        type: "#",
        feedsInto: ["Startup Budget", "Cash Flow"],
        question: "Legal and incorporation costs: Attorney fees, state filing fees, cooperative formation costs, bylaws drafting.",
        example: "$3,500 — cooperative attorney for bylaws and articles of incorporation ($2,500), Michigan state filing fees ($200), IRS EIN and tax registration ($0), accountant for initial setup ($800)",
        multiline: true,
      },
      {
        id: "P8-05",
        type: "#",
        feedsInto: ["Startup Budget", "P&L", "Cash Flow"],
        question: "Technology and software: Website, scheduling system, billing software, communication tools.",
        example: "$1,800 first year — website ($600 build + $150/year hosting), care scheduling software ($80/month = $960/year), email and communication tools ($90/year)",
        multiline: true,
      },
      {
        id: "P8-06",
        type: "#",
        feedsInto: ["Startup Budget", "P&L", "Cash Flow"],
        question: "Insurance: Business liability, workers' compensation, professional liability. Get real quotes.",
        example: "$680/month — general liability ($120/mo), workers' comp ($400/mo for 6 caregivers), professional liability/bonding ($160/mo)",
        multiline: true,
      },
      {
        id: "P8-07",
        type: "#",
        feedsInto: ["Startup Budget", "Cash Flow"],
        question: "Contingency and emergency fund: How much do you want in reserve before you open the doors? (Recommended: 3 months of operating expenses.)",
        example: "$15,000 — approximately 3 months of projected operating costs before client revenue stabilizes",
        multiline: false,
      },
      {
        id: "P8-10",
        type: "#",
        feedsInto: ["Startup Budget", "Cash Flow", "Executive Summary"],
        question: "Add it up: What is your total startup capital needed? (Sum of all the above.)",
        example: "$25,100 total startup capital needed",
        multiline: false,
      },
      {
        id: "P8-11",
        type: "N",
        feedsInto: ["Startup Budget", "Cash Flow", "Executive Summary"],
        question: "How will you fund your startup costs? Be specific about sources — member buy-ins, grants, CDFI loans, community investment, personal savings.",
        example: "Member buy-ins: 6 x $500 = $3,000. CDFI loan application to Michigan Women's Foundation: $10,000. Grant application to Consumers Energy Foundation (cooperative development): $7,000. The Fledge emergency fund bridge loan: $5,100. Total: $25,100.",
        multiline: true,
      },
      {
        id: "P8-09",
        type: "N",
        feedsInto: ["Startup Budget", "Ecosystem Map"],
        question: "Which Fledge ecosystem resources will you use? (Maker space, coaching, food systems, energy, tech programs, 99 Problems forum, etc.)",
        example: "Weekly Entrepreneurial Journey coaching sessions, 99 Problems forum for problem-solving, Fledge meeting space, connections to CDFI partners and cooperative legal support.",
        multiline: true,
      },
    ],
  },
  {
    id: "P9",
    title: "Part Nine: Partners — Building the Ecosystem",
    description: "One co-op is a good business. A network of co-ops is a local economy. No co-op thrives in isolation. Every partnership you build is a link in a larger chain that keeps value circulating locally.",
    fields: [
      {
        id: "P9-01",
        type: "N",
        feedsInto: ["Canvas", "Ecosystem Map", "P&L"],
        question: "Who are your key supplier partners? Who provides the inputs your co-op needs? Can you source locally? Name specific organizations or businesses.",
        example: "Sparrow Health System (refers clients post-discharge), Michigan Home Care & Hospice Association (training and certification resources), local medical supply company for equipment, Urbandale Farm for client food delivery referrals.",
        multiline: true,
      },
      {
        id: "P9-02",
        type: "N",
        feedsInto: ["Canvas", "Ecosystem Map"],
        question: "Who are your collaborator partners? Who does complementary work that you could combine with yours for greater impact?",
        example: "CATA (transit) — coordinating transportation for clients. Meals on Wheels — joint client outreach. Healthy Homes (energy efficiency for low-income households) — referral partnership for clients who need weatherization.",
        multiline: true,
      },
      {
        id: "P9-03",
        type: "N",
        feedsInto: ["Canvas", "Ecosystem Map", "Pitch"],
        question: "Who are your community anchor partners? Organizations or institutions that connect you to the people you serve.",
        example: "Area Agency on Aging of Ingham County, Sparrow Hospital social work department, MSU Extension, Eastside Neighborhood Organization, True Bethel Baptist Church.",
        multiline: true,
      },
      {
        id: "P9-04",
        type: "N",
        feedsInto: ["Ecosystem Map", "Canvas"],
        question: "Which other co-ops are in your ecosystem — current or target? How do you plan to connect and collaborate?",
        example: "Urbandale Farm (food), Sunshine House (housing), future energy co-op (Project 2026 pipeline). We plan to cross-refer clients and members, share purchasing where possible, and attend monthly Project 2026 co-op network meetings together.",
        multiline: true,
      },
      {
        id: "P9-05",
        type: "#",
        feedsInto: ["Scorecard", "Ecosystem Map"],
        question: "What percentage of your supplies and inputs do you aim to source from local partners? Set a target.",
        example: "75% of supplies sourced from Michigan-based vendors within Year 1. 90% by Year 3.",
        multiline: false,
      },
      {
        id: "P9-06",
        type: "N",
        feedsInto: ["Ecosystem Map", "Executive Summary", "Canvas"],
        question: "Describe your value-trapping strategy. How do your partnerships keep money circulating in the community instead of leaking out?",
        example: "We buy supplies from local vendors. We refer clients to local co-ops for food and housing. Our worker-owners spend their wages locally. We bank at a community credit union. Every dollar we earn cycles through Lansing at least twice before it leaves.",
        multiline: true,
      },
    ],
  },
  {
    id: "P10",
    title: "Part Ten: Revenue, Pricing, and Key Activities",
    description: "Knowing what to do is one thing. Knowing what you charge, what it costs, and doing it in the right order — that's how a co-op stays alive.",
    fields: [
      {
        id: "P10-01",
        type: "N",
        feedsInto: ["P&L", "Canvas", "Executive Summary"],
        question: "List every product or service your co-op sells or provides. Be specific — name each one separately.",
        example: "1. Personal care services (bathing, dressing, grooming) — billed by the hour. 2. Homemaker services (cleaning, laundry, meal prep) — billed by the hour. 3. Companionship and supervision — billed by the hour. 4. Transportation to medical appointments — billed by the mile + hourly.",
        multiline: true,
      },
      {
        id: "P10-02",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Startup Budget"],
        question: "What do you charge for each product or service? List price per unit (per hour, per item, per visit).",
        example: "Personal care: $22/hour. Homemaker services: $20/hour. Companionship: $18/hour. Transportation: $0.65/mile + $18/hour wait time.",
        multiline: true,
      },
      {
        id: "P10-03",
        type: "#",
        feedsInto: ["P&L", "Startup Budget"],
        question: "What does it cost you to deliver each product or service? (Labor + materials + overhead per unit.)",
        example: "Labor cost: $18.50/hour (living wage). Add 30% for workers' comp, payroll taxes, insurance overhead = effective labor cost of $24.05/hour. Vehicle cost: $0.40/mile. Net: we need to bill at or above $24/hour to cover costs before surplus.",
        multiline: true,
      },
      {
        id: "P10-04",
        type: "#",
        feedsInto: ["P&L", "Cash Flow"],
        question: "How many units do you project selling per month in Year 1? (Hours of service, items sold, visits, etc.)",
        example: "Month 1–3: 300 hours/month (6 workers averaging 50 billable hours each). Month 4–6: 480 hours/month as referrals build. Month 7–12: 600 hours/month at near-capacity for 6 workers.",
        multiline: true,
      },
      {
        id: "P10-05",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Executive Summary", "Startup Budget"],
        question: "What is your projected total monthly revenue in Year 1? (Price x units = revenue. Use your Month 6 estimate as your steady-state target.)",
        example: "Year 1 average: $9,600/month (480 hours x $20 blended rate). Low months (1–3): $6,000. Target steady state (Month 6+): $13,200/month (600 hrs x $22 blended).",
        multiline: true,
      },
      {
        id: "P10-06",
        type: "#",
        feedsInto: ["P&L", "Cash Flow"],
        question: "What is your projected monthly revenue in Year 2?",
        example: "$18,000/month — 10 worker-owners averaging 55 billable hours each at a blended rate of $20.50",
        multiline: false,
      },
      {
        id: "P10-07",
        type: "#",
        feedsInto: ["P&L", "Cash Flow"],
        question: "What is your projected monthly revenue in Year 3?",
        example: "$26,400/month — 15 worker-owners at 55 billable hours, blended rate of $22",
        multiline: false,
      },
      {
        id: "P10-08",
        type: "#",
        feedsInto: ["P&L", "Startup Budget", "Cash Flow", "Equity Schedule"],
        question: "What is your total monthly labor cost? (All worker-owner wages combined, including any additional workers.)",
        example: "Year 1: $8,880/month (6 workers x avg 40 hours/week x $18.50/hr x 4.33 weeks). Note: not all hours are billable — budget for training, travel, admin time.",
        multiline: true,
      },
      {
        id: "P10-09",
        type: "#",
        feedsInto: ["P&L", "Startup Budget", "Cash Flow"],
        question: "What are your other monthly operating costs? (Everything except labor — utilities, supplies, software, insurance, marketing, vehicle costs.)",
        example: "$2,480/month — insurance $680, vehicle costs $600, supplies $200, software $80, marketing $400, misc admin $520",
        multiline: true,
      },
      {
        id: "P10-10",
        type: "N",
        feedsInto: ["Executive Summary"],
        question: "NOW — What will your founding group do THIS WEEK? List 3–5 concrete, immediate actions. These require no preparation. Do them now.",
        example: "1. File for EIN with the IRS (free, online, 10 minutes). 2. Contact cooperative attorney for initial consultation. 3. Email Area Agency on Aging contact to announce our launch. 4. Set up a shared Google Drive for founding documents. 5. Schedule first official founding member meeting.",
        multiline: true,
      },
      {
        id: "P10-11",
        type: "N",
        feedsInto: ["Executive Summary"],
        question: "NEXT — What will you accomplish THIS MONTH? These require some planning or coordination.",
        example: "1. Complete cooperative bylaws draft with attorney. 2. Submit CDFI loan application. 3. Apply for Michigan state cooperative incorporation. 4. Set up care management software and begin onboarding process. 5. Confirm first two clients through Area Agency referral.",
        multiline: true,
      },
      {
        id: "P10-12",
        type: "N",
        feedsInto: ["Executive Summary"],
        question: "LATER — What are the bigger moves for THIS YEAR? These need resources, relationships, or more time.",
        example: "1. Onboard first 3 non-founding worker-owners through full membership pathway. 2. Achieve Medicaid waiver provider certification. 3. Hold first annual member meeting with full financial transparency report. 4. Establish formal partnership agreements with Urbandale Farm and Sunshine House. 5. Begin planning for Year 2 expansion.",
        multiline: true,
      },
      {
        id: "P10-13",
        type: "N",
        feedsInto: ["Executive Summary", "Pitch"],
        question: "ULTIMATELY — What does the big dream look like? What does perfect execution of this vision produce?",
        example: "A network of 40+ worker-owners earning living wages with full benefits, owning their jobs and their futures. Neighbors Care is the model that proved cooperative home care works in Lansing — and the template that gets replicated in Flint, Detroit, and Grand Rapids.",
        multiline: true,
      },
    ],
  },
  {
    id: "P11",
    title: "Part Eleven: Legal and Governance Structure",
    description: "Democracy isn't something you bolt onto a business. It's something you build from the foundation up. This section covers legal structure, the ICA Seven Cooperative Principles in practice, and how decisions get made.",
    fields: [
      {
        id: "P11-01",
        type: "N",
        feedsInto: ["Governance Summary", "Executive Summary"],
        question: "In which state will you incorporate your cooperative?",
        example: "Michigan. Michigan has a strong cooperative statute (Michigan Compiled Laws §450.3000+) that allows for worker cooperative incorporation with democratic governance built into the legal structure.",
        multiline: false,
      },
      {
        id: "P11-02",
        type: "N",
        feedsInto: ["Governance Summary", "Executive Summary"],
        question: "What legal entity type will you use? (Worker cooperative corporation, LLC with cooperative operating agreement, etc.)",
        example: "Michigan Worker Cooperative Corporation under the Michigan Cooperative Corporation Act. This gives us the clearest legal protection for our one-member, one-vote structure and patronage distribution.",
        multiline: true,
      },
      {
        id: "P11-03",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "ICA Principle 1 — Voluntary and Open Membership: How does your co-op embody this principle? Who can join, and are there any restrictions?",
        example: "Any worker who completes our probationary period and cooperative education program is eligible for membership. We do not discriminate based on race, gender, disability, immigration status, or background. The only requirement is commitment to our values and willingness to be an owner.",
        multiline: true,
      },
      {
        id: "P11-03b",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "ICA Principle 2 — Democratic Member Control: How do you practice one member, one vote in your co-op?",
        example: "Every worker-owner has exactly one vote in all major decisions, regardless of seniority or hours worked. The board is elected by the full membership. Major financial decisions require a full membership vote.",
        multiline: true,
      },
      {
        id: "P11-03c",
        type: "N",
        feedsInto: ["Governance Summary", "Equity Schedule"],
        question: "ICA Principle 3 — Member Economic Participation: How do members contribute to and share in the co-op's financial life?",
        example: "Members contribute through their $500 buy-in and through their labor. Surplus is distributed as patronage based on hours worked. Members share in both profits and any losses proportionally.",
        multiline: true,
      },
      {
        id: "P11-03d",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "ICA Principle 4 — Autonomy and Independence: How do you protect the co-op's independence from outside control?",
        example: "No outside investor holds any ownership or governance power. If we take outside funding (grants or loans), we ensure no strings attached that would compromise member control. Bylaws require a supermajority to change fundamental governance structure.",
        multiline: true,
      },
      {
        id: "P11-03e",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "ICA Principle 5 — Education, Training, and Information: How do you invest in member knowledge and cooperative literacy?",
        example: "Mandatory cooperative education for all new members. Monthly open-book financial review at member meetings. Annual governance training. We share our model openly with other co-ops and aspiring cooperators.",
        multiline: true,
      },
      {
        id: "P11-03f",
        type: "N",
        feedsInto: ["Governance Summary", "Ecosystem Map"],
        question: "ICA Principle 6 — Cooperation Among Cooperatives: How do you connect with and support other co-ops?",
        example: "Active participation in the Project 2026 co-op network. Cross-referrals with Urbandale Farm and Sunshine House. Commitment to mentor new co-ops forming in Lansing. Member of the US Federation of Worker Cooperatives.",
        multiline: true,
      },
      {
        id: "P11-03g",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard", "Executive Summary"],
        question: "ICA Principle 7 — Concern for Community: How does your co-op serve the broader community beyond its members and customers?",
        example: "20% of annual surplus allocated to community benefit. Public annual impact report. Living wages that keep money in local economy. Priority service to Medicaid clients who couldn't otherwise afford quality care.",
        multiline: true,
      },
      {
        id: "P11-04",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "How is your board of directors composed? How are members elected, and how long do they serve?",
        example: "5-member board, all worker-owners, elected by the full membership at the annual meeting. 2-year staggered terms so there is always continuity. Board meets monthly. Full membership meets monthly as well.",
        multiline: true,
      },
      {
        id: "P11-05",
        type: "#",
        feedsInto: ["Governance Summary"],
        question: "How many seats are on your governing board?",
        example: "5 seats",
        multiline: false,
      },
      {
        id: "P11-06",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "How are decisions made? Describe your voting structure for different types of decisions.",
        example: "Day-to-day operations: managed by rotating management team, no vote needed. Decisions under $500: board decides. Decisions $500–$2,500: board decides with member notification. Decisions over $2,500, new member admissions, bylaw changes, major partnerships: full membership vote, simple majority. Bylaw amendments: two-thirds supermajority.",
        multiline: true,
      },
      {
        id: "P11-07",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "What decisions require a full member vote? List the specific categories.",
        example: "Admission of new members. Expulsion of members. Changes to bylaws. Major capital expenditures over $2,500. Taking on debt over $5,000. Entering or exiting major partnerships. Changes to wage structure or patronage formula. Dissolution of the co-op.",
        multiline: true,
      },
      {
        id: "P11-08",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "What can the board decide independently without a full member vote?",
        example: "Operational decisions under $500. Scheduling and staffing. Client intake. Standard vendor contracts. Emergency expenditures under $1,000 with immediate member notification.",
        multiline: true,
      },
      {
        id: "P11-09",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "How often does the full membership meet? What is the standing agenda?",
        example: "Monthly member meeting, first Tuesday of the month. Standing agenda: financial report (open books), operational updates, member concerns, votes on pending decisions, one education topic per meeting.",
        multiline: true,
      },
      {
        id: "P11-10",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "How does your co-op handle disputes between members? Describe your conflict resolution process.",
        example: "Step 1: direct conversation between parties. Step 2: peer mediation with a neutral member. Step 3: board review and binding recommendation. Step 4: full membership vote if unresolved. We never let a conflict fester — it must enter the process within 30 days.",
        multiline: true,
      },
      {
        id: "P11-11",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "List the key sections of your bylaws. Which are drafted, in progress, or not yet started?",
        example: "Drafted: membership eligibility, voting procedures, board composition, meeting requirements. In progress: patronage distribution formula, member expulsion process, dissolution clause. Not started: amendment procedures, officer roles and duties.",
        multiline: true,
      },
      {
        id: "P11-12",
        type: "N",
        feedsInto: ["Governance Summary", "Equity Schedule", "P&L"],
        question: "How will surplus be distributed among members? Describe your patronage distribution method.",
        example: "Patronage dividends allocated based on hours worked during the fiscal year. A member who worked 2,000 hours receives twice the patronage allocation of a member who worked 1,000 hours. Distributed annually after the year-end financial review.",
        multiline: true,
      },
      {
        id: "P11-13",
        type: "#",
        feedsInto: ["Equity Schedule", "P&L"],
        question: "What percentage of annual surplus goes into individual member capital accounts?",
        example: "40% of annual surplus allocated to member capital accounts as patronage dividends.",
        multiline: false,
      },
      {
        id: "P11-14",
        type: "#",
        feedsInto: ["Equity Schedule", "P&L", "Startup Budget"],
        question: "What percentage of annual surplus is retained by the co-op as collective savings?",
        example: "40% retained as collective reserves for growth, resilience, and shared infrastructure. 20% allocated to community benefit programs.",
        multiline: false,
      },
    ],
  },
  {
    id: "P12",
    title: "Part Twelve: Financial Plan — In Plain English",
    description: "You don't need to be an accountant to understand your finances. You need to know: how much comes in, how much goes out, and what's left. When you complete this section, you'll have everything needed to generate your P&L, Cash Flow, Startup Budget, and Member Equity Schedule.",
    fields: [
      {
        id: "P12-01",
        type: "#",
        feedsInto: ["P&L", "Cash Flow"],
        question: "How much money do you expect to bring in during Month 1? (Your total revenue — everything customers pay you.)",
        example: "$6,000 — 300 hours of service at a blended rate of $20/hour. We're starting slow and building our client base through referrals.",
        multiline: false,
      },
      {
        id: "P12-02",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Startup Budget"],
        question: "How much will you pay in wages in Month 1? (Every worker-owner and any other workers, total.)",
        example: "$8,880 — 6 worker-owners averaging 40 hours/week at $18.50/hour including both billable and non-billable time (training, travel, admin). Note: Month 1 wages exceed revenue — this is expected and covered by startup capital.",
        multiline: false,
      },
      {
        id: "P12-03",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Startup Budget"],
        question: "What will you pay for your space in Month 1? (Rent, lease, or facility costs.)",
        example: "$0 — operating from members' homes. Using The Fledge for meetings at no cost.",
        multiline: false,
      },
      {
        id: "P12-04",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Startup Budget"],
        question: "What will you spend on supplies and materials in Month 1?",
        example: "$800 — initial supply purchase (cleaning products, PPE, care supplies). Ongoing months: approximately $200/month.",
        multiline: false,
      },
      {
        id: "P12-05",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Startup Budget"],
        question: "What are all your other costs in Month 1? (Insurance, software, marketing, vehicle, admin — everything else.)",
        example: "$2,480 — insurance $680, vehicle $600, software $80, marketing $400, admin/misc $520, plus $200 for equipment lease first payment.",
        multiline: false,
      },
      {
        id: "P12-06",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Equity Schedule"],
        question: "Subtract all your costs from your revenue. What's left — or what's the gap?",
        example: "Month 1 gap: $6,000 revenue − $12,160 total costs = ($6,160) deficit. This is covered by startup capital. We project break-even by Month 5 as client volume builds.",
        multiline: true,
      },
      {
        id: "P12-07",
        type: "#",
        feedsInto: ["P&L", "Cash Flow", "Executive Summary"],
        question: "Which month do you expect revenue to fully cover all your costs for the first time? (Your break-even month.)",
        example: "Month 5. By then we project 420 billable hours at $20 blended rate = $8,400 revenue against $10,560 total costs. Full break-even at 480 hours = Month 6.",
        multiline: true,
      },
      {
        id: "P12-08",
        type: "#",
        feedsInto: ["Equity Schedule", "Cash Flow"],
        question: "When you have a surplus — money left after all costs — how much goes to member capital accounts? (Use your percentage from Part 11.)",
        example: "40% of any monthly surplus goes to member capital accounts, allocated by hours worked. Example: $2,000 surplus → $800 to member accounts divided proportionally among 6 members = $133/member average.",
        multiline: true,
      },
      {
        id: "P12-09",
        type: "#",
        feedsInto: ["Equity Schedule", "Cash Flow", "Startup Budget"],
        question: "How much of each month's surplus stays in the co-op as collective savings?",
        example: "40% stays in co-op reserves. 20% to community benefit fund. Example: $2,000 surplus → $800 to reserves, $400 to community fund.",
        multiline: true,
      },
      {
        id: "P12-10",
        type: "#",
        feedsInto: ["P&L", "Executive Summary"],
        question: "What is your total projected revenue across all 12 months of Year 1?",
        example: "$115,200 — averaging $9,600/month across 12 months (low early months, higher later months as volume builds)",
        multiline: false,
      },
      {
        id: "P12-11",
        type: "#",
        feedsInto: ["P&L", "Executive Summary"],
        question: "What are your total projected expenses across all 12 months of Year 1?",
        example: "$137,280 — labor $106,560 + operating costs $30,720. Year 1 is a deficit year covered by startup capital.",
        multiline: false,
      },
      {
        id: "P12-12",
        type: "#",
        feedsInto: ["P&L", "Executive Summary", "Equity Schedule"],
        question: "Subtract total expenses from total revenue. What is your Year 1 surplus or deficit?",
        example: "($22,080) deficit in Year 1. This is planned and covered by $25,100 startup capital. We retain $3,020 of startup capital as emergency reserve entering Year 2.",
        multiline: true,
      },
      {
        id: "P12-13",
        type: "N",
        feedsInto: ["Executive Summary", "P&L"],
        question: "What is the biggest financial risk your co-op faces? Be honest.",
        example: "Slower-than-projected client growth. If we only reach 300 billable hours/month by Month 6 instead of 480, we burn through startup capital faster. Second risk: a key worker-owner leaving before we hit break-even.",
        multiline: true,
      },
      {
        id: "P12-14",
        type: "N",
        feedsInto: ["Executive Summary", "Startup Budget"],
        question: "What is your plan to manage that risk?",
        example: "We maintain a 3-month operating reserve at all times. We diversify our referral sources from day one — not relying on any single partner. We build the membership pipeline so we're always training the next worker-owner before we need them.",
        multiline: true,
      },
    ],
  },
  {
    id: "P13",
    title: "Part Thirteen: The Cooperative Compass",
    description: "This is the check-in you run regularly — monthly, quarterly, annually — to make sure your co-op is still pointing in the right direction. These are the questions and targets your founding group set when you were clear-eyed and committed.",
    fields: [
      {
        id: "P13-01",
        type: "N",
        feedsInto: ["Scorecard", "Governance Summary"],
        question: "People KPI 1: Name a specific, measurable goal for how people are treated in your co-op. How will you measure it?",
        example: "Every worker-owner earns at or above the Lansing living wage ($18.50/hour) from Day 1 of full membership. Measured: monthly payroll review. Target: 100% compliance always.",
        multiline: true,
      },
      {
        id: "P13-02",
        type: "N",
        feedsInto: ["Scorecard", "Governance Summary"],
        question: "People KPI 2: A second people metric — worker satisfaction, turnover rate, benefit access, or other.",
        example: "Worker-owner satisfaction score of 8/10 or above on quarterly anonymous survey. If score drops below 7, emergency member meeting within 30 days to address root causes.",
        multiline: true,
      },
      {
        id: "P13-03",
        type: "N",
        feedsInto: ["Scorecard"],
        question: "Planet KPI 1: A specific, measurable environmental goal.",
        example: "80% of supplies sourced from Michigan-based vendors by end of Year 1. Tracked quarterly through purchasing records.",
        multiline: true,
      },
      {
        id: "P13-04",
        type: "N",
        feedsInto: ["Scorecard"],
        question: "Planet KPI 2: A second environmental metric.",
        example: "At least 50% of client transportation miles completed in fuel-efficient or hybrid vehicles by end of Year 2. Tracked through mileage logs.",
        multiline: true,
      },
      {
        id: "P13-05",
        type: "N",
        feedsInto: ["Scorecard", "P&L"],
        question: "Profit KPI 1: A financial health target.",
        example: "Break-even (revenue covers all costs) by Month 6. Measured monthly against projected break-even milestone.",
        multiline: true,
      },
      {
        id: "P13-06",
        type: "N",
        feedsInto: ["Scorecard", "P&L"],
        question: "Profit KPI 2: A second financial metric.",
        example: "3-month operating reserve maintained at all times after break-even. If reserve drops below 2 months, board convenes emergency financial review within 2 weeks.",
        multiline: true,
      },
      {
        id: "P13-07",
        type: "N",
        feedsInto: ["Scorecard", "Governance Summary"],
        question: "Ownership KPI 1: A governance health metric.",
        example: "80% or more of worker-owners participating in all major governance votes. Tracked at every member meeting. If participation drops below 60% for two consecutive meetings, facilitated conversation to understand and address barriers.",
        multiline: true,
      },
      {
        id: "P13-08",
        type: "N",
        feedsInto: ["Scorecard", "Governance Summary", "Equity Schedule"],
        question: "Ownership KPI 2: An equity-building metric.",
        example: "Each worker-owner's capital account grows by at least $500/year starting Year 2. Reviewed annually at financial report meeting. This is the wealth-building promise we made — we track whether we're keeping it.",
        multiline: true,
      },
      {
        id: "P13-09",
        type: "N",
        feedsInto: ["Governance Summary", "Scorecard"],
        question: "How often will your co-op run a full four-bottom-line review? Who leads it?",
        example: "Quarterly — at the last member meeting of each quarter. Facilitated by rotating member so no single voice dominates. Annual deep review at year-end with guest facilitator from The Fledge.",
        multiline: true,
      },
      {
        id: "P13-10",
        type: "N",
        feedsInto: ["Governance Summary"],
        question: "Who is responsible for gathering the data and preparing the compass report for each meeting?",
        example: "The board secretary prepares the scorecard data one week before each quarterly meeting and shares it with all members in advance. No surprises at the meeting — everyone comes prepared.",
        multiline: true,
      },
    ],
  },
];

export function getSection(id: string): HandbookSection | undefined {
  return HANDBOOK.find((s) => s.id === id);
}

export function getAllFieldIds(): string[] {
  return HANDBOOK.flatMap((s) => s.fields.map((f) => f.id));
}
